## Basic Configuration

baseurl = "https://mgallow.github.io/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

contentdir = "content"
layoutdir = "layouts"
#publishdir = "../MGallow.github.io"

author = "Matt Galloway"
title = "Matt Galloway, University of Minnesota"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-84680750-2"
enableRobotsTXT = true

## Site Settings
[params]
author = "Matt Galloway"
intro = "Statistics Ph.D Student"
description = "University of Minnesota <br/> Minneapolis, MN"
authorimage = "headshot.jpg"
dateformat = "June 5, 2018"

## Site Meta Settings
[params.meta]
description = "Matt Galloway"
keywords = "Matt, Galloway, Minnesota, University, Statistics"

## Social Accounts
[params.social]
github = "MGallow"
#instagram = "<username>"
#xing = "<username>"
linkedin = "mattgalloway2"
twitter = "MCGallow"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
email = "gall0441@umn.edu"

## Extras
[params.extra]
copyright = "Â© 2018. Matt Galloway. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "Publications"
    weight = 300
    identifier = "publications"
    url = "/publications/"
[[menu.main]]
    name = "Research"
    weight = 400
    identifier = "research"
    url = "/research/"
[[menu.main]]
    name = "Posts"
    weight = 600
    identifier = "posts"
    url = "/posts/"
